"""Added background_color to Workspace

Revision ID: 800677fa70d0
Revises: d35e174da081
Create Date: 2025-02-13 12:50:32.019993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800677fa70d0'
down_revision = 'd35e174da081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_column('background_color')

    # ### end Alembic commands ###
