"""Fixing migration issues

Revision ID: d35e174da081
Revises: f6557ed1fb72
Create Date: 2025-02-13 12:15:14.553161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd35e174da081'
down_revision = 'f6557ed1fb72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_workspace')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_workspace',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('privacy', sa.VARCHAR(length=10), nullable=False),
    sa.Column('state', sqlite.JSON(), nullable=True),
    sa.Column('invite_code', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code', name='uq_workspace_invite_code')
    )
    # ### end Alembic commands ###
