"""added invite_code to workspace

Revision ID: f6557ed1fb72
Revises: 4e43b1757a54
Create Date: 2025-02-13 11:28:21.062031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6557ed1fb72'
down_revision = '4e43b1757a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code', sa.String(length=36), nullable=True))
        with op.batch_alter_table('workspace', schema=None) as batch_op:
            batch_op.add_column(sa.Column('invite_code', sa.String(length=36), nullable=True))
            batch_op.create_unique_constraint("uq_workspace_invite_code", ['invite_code'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('invite_code')

    # ### end Alembic commands ###
